#!/usr/bin/env python3
"""
Script to visualize profiling results from the CSV generated by analyze_profiling.py.
Creates bar charts for average execution time and maximum percentage of total runtime.
Supports both exclusive and inclusive profiling modes.

Configuration:
  Edit TIMESTEPS and MODE at the top of this script:
  TIMESTEPS = 10   # Analyze profile_10 directory
  TIMESTEPS = 100  # Analyze profile_100 directory
  MODE = 'excl'    # 'excl' for exclusive, 'incl' for inclusive, 'both' for both
  MODE = 'incl'
  MODE = 'both'

Output:
  PNG plots saved to: profile_{TIMESTEPS}/ directory
  Supports both exclusive and inclusive profiling modes
"""

import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import numpy as np

# ===== CONFIGURATION =====
# Set timesteps to analyze: 10 or 100
TIMESTEPS = 10
# Set visualization mode: 'excl' (exclusive), 'incl' (inclusive), or 'both'
MODE = 'both'
# =======================

# Font sizes for plots
font_s = 14        # Base font size for labels, legend
font_title = 16    # Title font size
font_xlabel = 12   # X-axis tick labels (smaller)
font_bar_label = 12  # Font size for value labels above bars

# Configuration order and color mapping (consistent across all plots)
CONFIG_ORDER = ['gc-to-gc', 'gc-to-surr', 'gc-to-hychem', 
                'surr-to-surr', 'surr-to-hychem', 'hychem-to-hychem']
CONFIG_COLORS = ["indigo", "rebeccapurple", "mediumpurple", "steelblue", "skyblue", "#7f7f7f"]

# Configuration display names (for labels and legends)
CONFIG_DISPLAY_NAMES = {
    'gc-to-gc': 'GC-to-GC',
    'gc-to-surr': 'GC-to-Surrogate',
    'gc-to-hychem': 'GC-to-HyChem',
    'surr-to-surr': 'Surrogate-to-Surrogate',
    'surr-to-hychem': 'Surrogate-to-HyChem',
    'hychem-to-hychem': 'HyChem-to-HyChem'
}

# Function colors for grouped bar plots
FUNCTION_COLORS = ["#063C61", "#2980B9", "#91BCD8","rebeccapurple", "#7f7f7f"]


def load_profiling_data(csv_file):
    """Load profiling data from CSV file."""
    df = pd.read_csv(csv_file)
    return df


def get_column_names(mode='excl'):
    """
    Get the appropriate column names based on profiling mode.
    
    Args:
        mode: 'excl' (exclusive) or 'incl' (inclusive)
        
    Returns:
        tuple: (avg_column, label_prefix)
    """
    if mode == 'incl':
        return 'Incl_Avg', 'Inclusive'
    else:  # excl
        return 'Excl_Avg', 'Exclusive'


def create_bar_plots(df, output_dir, mode='excl'):
    """
    Create bar plots for Avg and Average Percentage for each function.
    
    Args:
        df: DataFrame with profiling data
        output_dir: Directory to save the plots
        mode: 'excl' (exclusive) or 'incl' (inclusive)
    """
    avg_col, label_prefix = get_column_names(mode)
    
    # Calculate percentage of runtime from averages
    df = df.copy()
    df['Avg_Pct'] = (df[avg_col] / df['Total_Time']) * 100
    
    # Get unique functions
    functions = df['Function'].unique()
    
    # Set up the color palette using consistent mapping
    # Create a dictionary for config -> color mapping
    color_map = {config: color for config, color in zip(CONFIG_ORDER, CONFIG_COLORS)}
    
    # Create figure with subplots for each function
    # Two columns: one for Avg, one for Avg_Pct
    n_functions = len(functions)
    fig, axes = plt.subplots(n_functions, 2, figsize=(16, 4*n_functions))
    
    # Ensure axes is 2D even if there's only one function
    if n_functions == 1:
        axes = axes.reshape(1, -1)
    
    for i, function in enumerate(functions):
        # Filter data for this function
        func_data = df[df['Function'] == function].copy()
        
        # Reorder by configuration
        func_data['Config_Order'] = pd.Categorical(
            func_data['Configuration'], 
            categories=CONFIG_ORDER, 
            ordered=True
        )
        func_data = func_data.sort_values('Config_Order')
        
        # Add display names for configurations
        func_data['Config_Display'] = func_data['Configuration'].map(CONFIG_DISPLAY_NAMES)
        
        # Get colors for this function's configurations
        bars_colors = [color_map[config] for config in func_data['Configuration']]
        
        # Plot Avg (left column)
        ax_time = axes[i, 0]
        bars_time = ax_time.bar(func_data['Config_Display'], func_data[avg_col], 
                                color=bars_colors)
        ax_time.set_ylabel('Average Time (s)', fontsize=font_s, fontweight='bold')
        ax_time.set_title(f'{function}\n{label_prefix} Average Time', 
                         fontsize=font_title, fontweight='bold')
        ax_time.tick_params(axis='x', rotation=45, labelsize=font_xlabel)
        ax_time.tick_params(axis='y', labelsize=font_s)
        ax_time.grid(axis='y', alpha=0.3, linestyle='--')
        
        # Add value labels on bars
        for bar in bars_time:
            height = bar.get_height()
            ax_time.text(bar.get_x() + bar.get_width()/2., height,
                        f'{height:.2f}',
                        ha='center', va='bottom', fontsize=font_bar_label)
        
        # Plot Avg_Pct (right column)
        ax_pct = axes[i, 1]
        bars_pct = ax_pct.bar(func_data['Config_Display'], func_data['Avg_Pct'], 
                              color=bars_colors)
        ax_pct.set_ylabel('Average % of Total Time', fontsize=font_s, fontweight='bold')
        ax_pct.set_title(f'{function}\nAverage Percentage of Runtime ({label_prefix})', 
                        fontsize=font_title, fontweight='bold')
        ax_pct.tick_params(axis='x', rotation=45, labelsize=font_xlabel)
        ax_pct.tick_params(axis='y', labelsize=font_s)
        ax_pct.grid(axis='y', alpha=0.3, linestyle='--')
        
        # Add value labels on bars
        for bar in bars_pct:
            height = bar.get_height()
            ax_pct.text(bar.get_x() + bar.get_width()/2., height,
                       f'{height:.2f}%',
                       ha='center', va='bottom', fontsize=font_bar_label)
    
    plt.tight_layout()
    
    # Save the combined figure
    suffix = 'incl' if mode == 'incl' else 'excl'
    output_file = output_dir / f'profiling_comparison_{suffix}.png'
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    print(f"Saved combined plot: {output_file}")
    
    plt.close()


def create_grouped_bar_plots(df, output_dir, mode='excl'):
    """
    Create grouped bar plots showing all functions side-by-side for each metric.
    
    Args:
        df: DataFrame with profiling data
        output_dir: Directory to save the plots
        mode: 'excl' (exclusive) or 'incl' (inclusive)
    """
    avg_col, label_prefix = get_column_names(mode)
    
    # Calculate percentage of runtime from averages
    df = df.copy()
    df['Avg_Pct'] = (df[avg_col] / df['Total_Time']) * 100
    
    # Get unique functions
    functions = sorted(df['Function'].unique())
    
    # Pivot the data for easier plotting
    pivot_time = df.pivot(index='Configuration', columns='Function', values=avg_col)
    pivot_pct = df.pivot(index='Configuration', columns='Function', values='Avg_Pct')
    
    # Reorder configurations
    pivot_time = pivot_time.reindex(CONFIG_ORDER)
    pivot_pct = pivot_pct.reindex(CONFIG_ORDER)
    
    # Replace configuration names with display names
    pivot_time.index = [CONFIG_DISPLAY_NAMES[config] for config in pivot_time.index]
    pivot_pct.index = [CONFIG_DISPLAY_NAMES[config] for config in pivot_pct.index]
    
    # Create figure for Avg
    suffix = 'incl' if mode == 'incl' else 'excl'
    fig, ax = plt.subplots(figsize=(14, 8))
    pivot_time.plot(kind='bar', ax=ax, width=0.8, color=FUNCTION_COLORS[:len(pivot_time.columns)])
    ax.set_xlabel('')
    ax.set_ylabel('Average Time (s)', fontsize=font_s, fontweight='bold')
    ax.set_title(f'{label_prefix} Average Time by Configuration and Function', 
                 fontsize=font_title, fontweight='bold')
    ax.legend(loc='upper right', fontsize=font_s)
    ax.tick_params(axis='x', rotation=45, labelsize=font_s)
    ax.tick_params(axis='y', labelsize=font_s)
    ax.grid(axis='y', alpha=0.3, linestyle='--')
    plt.tight_layout()
    
    output_file_time = output_dir / f'profiling_{suffix}_avg_grouped.png'
    plt.savefig(output_file_time, dpi=300, bbox_inches='tight')
    print(f"Saved grouped {label_prefix}_Avg plot: {output_file_time}")
    plt.close()
    
    # Create figure for Avg_Pct
    fig, ax = plt.subplots(figsize=(14, 8))
    pivot_pct.plot(kind='bar', ax=ax, width=0.8, color=FUNCTION_COLORS[:len(pivot_pct.columns)])
    ax.set_xlabel('')
    ax.set_ylabel('Average % of Total Time', fontsize=font_s, fontweight='bold')
    ax.set_title(f'Average Percentage of Runtime by Configuration and Function ({label_prefix})', 
                 fontsize=font_title, fontweight='bold')
    ax.get_legend().remove()
    ax.tick_params(axis='x', rotation=45, labelsize=font_s)
    ax.tick_params(axis='y', labelsize=font_s)
    ax.grid(axis='y', alpha=0.3, linestyle='--')
    plt.tight_layout()
    
    output_file_pct = output_dir / f'profiling_avg_pct_grouped_{suffix}.png'
    plt.savefig(output_file_pct, dpi=300, bbox_inches='tight')
    print(f"Saved grouped Avg_Pct plot ({label_prefix}): {output_file_pct}")
    plt.close()
    
    # Create combined figure with horizontal subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(24, 8))
    
    # Plot Avg (left)
    pivot_time.plot(kind='bar', ax=ax1, width=0.8, color=FUNCTION_COLORS[:len(pivot_time.columns)])
    ax1.set_xlabel('')
    ax1.set_ylabel('Average Time (s)', fontsize=font_s, fontweight='bold')
    ax1.set_title(f'{label_prefix} Average Time by Configuration and Function', 
                  fontsize=font_title, fontweight='bold')
    ax1.tick_params(axis='x', rotation=45, labelsize=font_s)
    ax1.tick_params(axis='y', labelsize=font_s)
    ax1.grid(axis='y', alpha=0.3, linestyle='--')
    ax1.legend(loc='upper right', fontsize=font_s)
    
    # Plot Avg_Pct (right)
    pivot_pct.plot(kind='bar', ax=ax2, width=0.8, color=FUNCTION_COLORS[:len(pivot_pct.columns)])
    ax2.set_xlabel('')
    ax2.set_ylabel('Average % of Total Time', fontsize=font_s, fontweight='bold')
    ax2.set_title(f'Average Percentage of Runtime by Configuration and Function ({label_prefix})', 
                  fontsize=font_title, fontweight='bold')
    ax2.tick_params(axis='x', rotation=45, labelsize=font_s)
    ax2.tick_params(axis='y', labelsize=font_s)
    ax2.grid(axis='y', alpha=0.3, linestyle='--')
    ax2.get_legend().remove()  # Remove legend from second subplot
    
    plt.tight_layout()
    
    output_file_combined = output_dir / f'profiling_combined_grouped_{suffix}.png'
    plt.savefig(output_file_combined, dpi=300, bbox_inches='tight')
    print(f"Saved combined grouped plot ({label_prefix}): {output_file_combined}")
    plt.close()


def create_individual_function_plots(df, output_dir, mode='exclusive'):
    """
    Create individual plots for each function showing both metrics.
    
    Args:
        df: DataFrame with profiling data
        output_dir: Directory to save the plots
        mode: 'excl' or 'incl'
    """
    avg_col, label_prefix = get_column_names(mode)
    
    # Calculate percentage of runtime from averages
    df = df.copy()
    df['Avg_Pct'] = (df[avg_col] / df['Total_Time']) * 100
    
    # Get unique functions
    functions = df['Function'].unique()
    
    # Create a dictionary for config -> color mapping
    color_map = {config: color for config, color in zip(CONFIG_ORDER, CONFIG_COLORS)}
    
    for function in functions:
        # Filter data for this function
        func_data = df[df['Function'] == function].copy()
        
        # Reorder by configuration
        func_data['Config_Order'] = pd.Categorical(
            func_data['Configuration'], 
            categories=CONFIG_ORDER, 
            ordered=True
        )
        func_data = func_data.sort_values('Config_Order')
        
        # Add display names for configurations
        func_data['Config_Display'] = func_data['Configuration'].map(CONFIG_DISPLAY_NAMES)
        
        # Get colors for this function's configurations
        bars_colors = [color_map[config] for config in func_data['Configuration']]
        
        # Create figure with two subplots
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
        
        # Plot Avg with custom colors
        bars1 = ax1.bar(func_data['Config_Display'], func_data[avg_col], 
                        color=bars_colors, alpha=0.8)
        ax1.set_ylabel('Average Time (s)', fontsize=font_s, fontweight='bold')
        ax1.set_title(f'{label_prefix} Average Time', fontsize=font_title, fontweight='bold')
        ax1.tick_params(axis='x', rotation=45, labelsize=font_xlabel)
        ax1.tick_params(axis='y', labelsize=font_s)
        ax1.grid(axis='y', alpha=0.3, linestyle='--')
        
        # Set y-axis limit to accommodate bar labels
        ymax1 = func_data[avg_col].max() * 1.2
        ax1.set_ylim(0, ymax1)
        
        # Add value labels
        for bar in bars1:
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.2f}',
                    ha='center', va='bottom', fontsize=font_bar_label)
        
        # Plot Avg_Pct with custom colors
        bars2 = ax2.bar(func_data['Config_Display'], func_data['Avg_Pct'], 
                        color=bars_colors, alpha=0.8)
        ax2.set_ylabel('Average % of Total Time', fontsize=font_s, fontweight='bold')
        ax2.set_title(f'Average Percentage of Runtime ({label_prefix})', fontsize=font_title, fontweight='bold')
        ax2.tick_params(axis='x', rotation=45, labelsize=font_xlabel)
        ax2.tick_params(axis='y', labelsize=font_s)
        ax2.grid(axis='y', alpha=0.3, linestyle='--')
        
        # Set y-axis limit to accommodate bar labels
        ymax2 = func_data['Avg_Pct'].max() * 1.2
        ax2.set_ylim(0, ymax2)
        
        # Add value labels
        for bar in bars2:
            height = bar.get_height()
            ax2.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.2f}%',
                    ha='center', va='bottom', fontsize=font_bar_label)
        
        # Add overall title
        fig.suptitle(f'{function}', fontsize=font_title, fontweight='bold', y=1.02)
        
        plt.tight_layout()
        
        # Save individual function plot
        # Clean function name for filename
        safe_name = function.replace('::', '_').replace('()', '').replace('/', '_')
        suffix = 'incl' if mode == 'incl' else 'excl'
        output_file = output_dir / f'profiling_{safe_name}_{suffix}.png'
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Saved individual plot ({label_prefix}): {output_file}")
        plt.close()


def create_total_time_plots(df, output_dir):
    """
    Create plots for total simulation time across configurations.
    
    Args:
        df: DataFrame with profiling data
        output_dir: Directory to save the plots
    """
    
    # Extract unique configurations and their total times
    config_times = df.groupby('Configuration')['Total_Time'].first()
    
    # Reorder according to CONFIG_ORDER
    config_times = config_times.reindex(CONFIG_ORDER)
    
    # Create display names for x-axis
    config_display = [CONFIG_DISPLAY_NAMES[config] for config in config_times.index]
    
    # Create figure with two subplots side-by-side
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 6))
    
    # --- LEFT PLOT: Absolute Total Time ---
    bars1 = ax1.bar(range(len(config_times)), config_times.values, 
                    color=CONFIG_COLORS[:len(config_times)], 
                    edgecolor='black', linewidth=1.5, alpha=0.8)
    
    ax1.set_xticks(range(len(config_times)))
    ax1.set_xticklabels(config_display, rotation=45, ha='right', fontsize=font_s)
    ax1.set_ylabel('Total Time (seconds)', fontsize=font_s, fontweight='bold')
    ax1.set_title('Total Simulation Time by Configuration', 
                  fontsize=font_title, fontweight='bold')
    ax1.tick_params(axis='y', labelsize=font_s)
    ax1.grid(axis='y', alpha=0.3, linestyle='--')
    ax1.set_axisbelow(True)
    
    # Add value labels on bars
    for i, (config, time) in enumerate(config_times.items()):
        ax1.text(i, time, f'{time:.1f}s', ha='center', va='bottom', 
                fontsize=font_bar_label, fontweight='bold')
    
    # --- RIGHT PLOT: Normalized (Slowdown relative to hychem-to-hychem) ---
    hychem_to_hychem_time = config_times['hychem-to-hychem']
    slowdown = config_times / hychem_to_hychem_time
    
    bars2 = ax2.bar(range(len(slowdown)), slowdown.values, 
                    color=CONFIG_COLORS[:len(slowdown)], 
                    edgecolor='black', linewidth=1.5, alpha=0.8)
    
    ax2.set_xticks(range(len(slowdown)))
    ax2.set_xticklabels(config_display, rotation=45, ha='right', fontsize=font_s)
    ax2.set_ylabel('Slowdown (×)', fontsize=font_s, fontweight='bold')
    ax2.set_title('Slowdown Relative to HyChem-to-HyChem', 
                  fontsize=font_title, fontweight='bold')
    ax2.tick_params(axis='y', labelsize=font_s)
    ax2.grid(axis='y', alpha=0.3, linestyle='--')
    ax2.set_axisbelow(True)
    
    # Add value labels on bars
    for i, (config, sd) in enumerate(slowdown.items()):
        ax2.text(i, sd, f'{sd:.2f}×', ha='center', va='bottom', 
                fontsize=font_bar_label, fontweight='bold')
    
    # Add baseline line at 1.0
    ax2.axhline(y=1.0, color='red', linestyle='--', linewidth=2, 
                alpha=0.5, label='HyChem-to-HyChem baseline')
    ax2.legend(fontsize=font_s)
    
    plt.tight_layout()
    
    # Save the plot
    output_path = output_dir / 'total_time_comparison.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Saved total time comparison plot: {output_path}")
    
    # Print summary statistics
    print("\n" + "="*80)
    print("TOTAL TIME SUMMARY")
    print("="*80)
    print(f"\nConfiguration Times:")
    for config, time in config_times.items():
        sd = slowdown[config]
        display_name = CONFIG_DISPLAY_NAMES[config]
        print(f"  {display_name:<30} {time:>10.2f} s    ({sd:>5.2f}× slowdown)")
    
    print(f"\nStatistics:")
    print(f"  Mean:        {config_times.mean():>10.2f} seconds")
    print(f"  Median:      {config_times.median():>10.2f} seconds")
    print(f"  Std Dev:     {config_times.std():>10.2f} seconds")
    min_config = config_times.idxmin()
    max_config = config_times.idxmax()
    max_slowdown_config = slowdown.idxmax()
    print(f"  Min:         {config_times.min():>10.2f} seconds ({CONFIG_DISPLAY_NAMES[min_config]})")
    print(f"  Max:         {config_times.max():>10.2f} seconds ({CONFIG_DISPLAY_NAMES[max_config]})")
    print(f"  Max Slowdown: {slowdown.max():>9.2f}× ({CONFIG_DISPLAY_NAMES[max_slowdown_config]})")
    
    plt.close()


def create_particle_count_plots(df, output_dir):
    """
    Create plots for initial particle counts across configurations.
    
    Args:
        df: DataFrame with profiling data
        output_dir: Directory to save the plots
    """
    
    # Extract unique configurations and their particle counts
    config_particles = df.groupby('Configuration')['Particles'].first()
    
    # Reorder according to CONFIG_ORDER
    config_particles = config_particles.reindex(CONFIG_ORDER)
    
    # Create display names for x-axis
    config_display = [CONFIG_DISPLAY_NAMES[config] for config in config_particles.index]
    
    # Create figure
    fig, ax = plt.subplots(figsize=(12, 6))
    
    # Plot particle counts
    bars = ax.bar(range(len(config_particles)), config_particles.values, 
                  color=CONFIG_COLORS[:len(config_particles)], 
                  edgecolor='black', linewidth=1.5, alpha=0.8)
    
    ax.set_xticks(range(len(config_particles)))
    ax.set_xticklabels(config_display, rotation=45, ha='right', fontsize=font_s)
    ax.set_ylabel('Number of Particles', fontsize=font_s, fontweight='bold')
    ax.set_title('Initial Particle Count by Configuration', 
                  fontsize=font_title, fontweight='bold')
    ax.tick_params(axis='y', labelsize=font_s)
    ax.grid(axis='y', alpha=0.3, linestyle='--')
    ax.set_axisbelow(True)
    
    # Add value labels on bars (formatted with thousands separator)
    for i, (config, count) in enumerate(config_particles.items()):
        ax.text(i, count, f'{int(count):,}', ha='center', va='bottom', 
                fontsize=font_bar_label, fontweight='bold')
    
    plt.tight_layout()
    
    # Save the plot
    output_path = output_dir / 'particle_count_comparison.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Saved particle count comparison plot: {output_path}")
    
    # Print summary statistics
    print("\n" + "="*80)
    print("PARTICLE COUNT SUMMARY")
    print("="*80)
    print(f"\nConfiguration Particle Counts:")
    for config, count in config_particles.items():
        display_name = CONFIG_DISPLAY_NAMES[config]
        print(f"  {display_name:<30} {int(count):>12,} particles")
    
    print(f"\nStatistics:")
    print(f"  Mean:        {config_particles.mean():>12,.0f} particles")
    print(f"  Median:      {config_particles.median():>12,.0f} particles")
    print(f"  Std Dev:     {config_particles.std():>12,.0f} particles")
    min_config = config_particles.idxmin()
    max_config = config_particles.idxmax()
    print(f"  Min:         {config_particles.min():>12,.0f} particles ({CONFIG_DISPLAY_NAMES[min_config]})")
    print(f"  Max:         {config_particles.max():>12,.0f} particles ({CONFIG_DISPLAY_NAMES[max_config]})")
    
    plt.close()


def main():
    # Setup paths
    base_dir = Path(__file__).parent
    profile_dir = base_dir / f'profile_{TIMESTEPS}'
    csv_file = profile_dir / f'profiling_analysis_summary_{TIMESTEPS}.csv'
    output_dir = profile_dir
    
    # Check if CSV exists
    if not csv_file.exists():
        print(f"Error: {csv_file} not found!")
        print(f"Please run analyze_profiling.py first to generate the CSV file.")
        return
    
    # Load data
    print(f"Loading data from {csv_file}...")
    df = load_profiling_data(csv_file)
    
    # Filter out calcDiffusivity (only present in gc-to-gc case, use getDiffusivity instead)
    df = df[df['Function'] != 'PeleLMeX::calcDiffusivity()']
    
    # Check if Total_Time column exists
    has_total_time = 'Total_Time' in df.columns
    has_particles = 'Particles' in df.columns
    
    # Create total time plots if available
    if has_total_time:
        print(f"\n{'='*80}")
        print(f"Generating TOTAL TIME visualizations...")
        print(f"{'='*80}\n")
        create_total_time_plots(df, output_dir)
    
    # Create particle count plots if available
    if has_particles:
        print(f"\n{'='*80}")
        print(f"Generating PARTICLE COUNT visualizations...")
        print(f"{'='*80}\n")
        create_particle_count_plots(df, output_dir)
    
    # Check which modes are available
    has_excl = 'Excl_Avg' in df.columns
    has_incl = 'Incl_Avg' in df.columns
    
    if not has_excl and not has_incl:
        print("Error: No profiling data found in CSV!")
        return
    
    # Determine which modes to generate
    modes_to_generate = []
    if MODE == 'both':
        if has_excl:
            modes_to_generate.append('excl')
        if has_incl:
            modes_to_generate.append('incl')
    else:
        # Check if requested mode is available
        if MODE == 'excl' and not has_excl:
            print("Error: Exclusive profiling data not found in CSV!")
            return
        if MODE == 'incl' and not has_incl:
            print("Error: Inclusive profiling data not found in CSV!")
            print("Please re-run analyze_profiling.py to extract inclusive profiling data.")
            return
        modes_to_generate.append(MODE)
    
    # Generate plots for each mode
    for mode in modes_to_generate:
        print(f"\n{'='*80}")
        print(f"Generating {mode.upper()} profiling visualizations...")
        print(f"{'='*80}\n")
        
        # Filter data for this mode
        df_mode = df.copy()
        if mode == 'excl':
            # Exclude Advance() from exclusive analysis (top of call stack)
            df_mode = df_mode[df_mode['Function'] != 'PeleLMeX::Advance()']
        
        # Create different types of plots
        create_bar_plots(df_mode, output_dir, mode)
        create_grouped_bar_plots(df_mode, output_dir, mode)
        create_individual_function_plots(df_mode, output_dir, mode)
    
    print("\n" + "="*80)
    print("VISUALIZATION COMPLETE")
    print("="*80)
    
    # Check if total time plot was created
    has_total_time = 'Total_Time' in df.columns
    
    if has_total_time:
        print("\nGenerated total time plot:")
        print("  - total_time_comparison.png - Absolute and normalized total simulation times")
        print()
    
    if len(modes_to_generate) == 1:
        mode = modes_to_generate[0]
        suffix = 'incl' if mode == 'incl' else 'excl'
        print(f"\nGenerated {mode} profiling plots:")
        print(f"  1. profiling_comparison_{suffix}.png - All functions in one combined view")
        print(f"  2. profiling_{suffix}_avg_grouped.png - Grouped bar chart for average time")
        print(f"  3. profiling_max_pct_grouped_{suffix}.png - Grouped bar chart for max percentage")
        print(f"  4. profiling_combined_grouped_{suffix}.png - Combined grouped plot with shared legend")
        print(f"  5. profiling_<function>_{suffix}.png - Individual plots for each function")
    else:
        print("\nGenerated both exclusive and inclusive profiling plots:")
        print(f"  Exclusive plots: *_excl.png")
        print(f"  Inclusive plots: *_incl.png")
    print()


if __name__ == '__main__':
    main()
